version: '3.8'

services:
  
  petclinic-backend:
    image: springcommunity/spring-petclinic-rest
    container_name: spring-petclinic-backend
    depends_on:
      - ocelot-agent
    ports:
      - "9966:9966"
    networks:
      - explorviz
    environment:
      - LANDSCAPE_TOKEN_ID=${LANDSCAPE_TOKEN_ID}
      - LANDSCAPE_TOKEN_SECRET=${LANDSCAPE_TOKEN_SECRET}
    volumes:
      - agent-vol:/agent
      - ./inspectit.yml:/agent/inspectit.yml
    # entrypoint:
    #   [
    #     "sh",
    #     "-c",
    #     'java -Dinspectit.config.file-based.path="/agent/" -javaagent:/agent/inspectit-ocelot-agent.jar -jar /app.jar',
    #   ]
    command: java -Dinspectit.config.file-based.path="/agent/" -javaagent:/agent/inspectit-ocelot-agent.jar -jar /app.jar



  ocelot-agent:
    image: inspectit/inspectit-ocelot-agent:2.1.1
    container_name: ocelot-agent-petclinic-backend
    networks:
      - explorviz
    volumes:
      - agent-vol:/agent


  petclinic-frontend:
    build:
      context: ./spring-petclinic-angular
      args:
        NODE_VERSION: 18.10.0
    ports:
      - ${EXTERNAL_PORT}:8080 #${EXTERNAL_PORT} = 18080
    environment:
      - LANDSCAPE_TOKEN_ID=${LANDSCAPE_TOKEN_ID}
      - LANDSCAPE_TOKEN_SECRET=${LANDSCAPE_TOKEN_SECRET}
    networks:
      - explorviz
    depends_on:
      - petclinic-backend

        
  # Collector
  collector:
    image: otel/opentelemetry-collector:latest
    hostname: node-collector      # eigene Benennung 
#    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "9464:9464"
      - "4317:4317"
      - "4318:4318"
      - "55670:55678" # zpages # was occupied
    networks:
      - explorviz
    # depends_on:
    #   - zipkin-all-in-on 


  # # Zipkin
  # zipkin-all-in-one:
  #   image: openzipkin/zipkin:latest
  #   hostname: zipkin
  #   ports:
  #     - "9411:9411"
  #   environment: 
  #     - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
  #   networks:
  #     - explorviz  


  # Prometheus
  # prometheus:
  #   image: prom/prometheus:latest
  #   hostname: prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - explorviz

volumes:
  agent-vol:

networks:
  explorviz:
    name: explorviz
    external: true