version: "2"
services:
  oc-agent:
    image: explorviz/ocagent:latest
    command: ["--config=/etc/oc-agent-config.yaml"]
    volumes:
      - ./oc-agent-config.yaml:/etc/oc-agent-config.yaml
    #ports:
    #  - 55678:55678
    # linux
    network_mode: host
