version: "2"
services:
  oc-agent:
    image: ocagent:latest
    command: ["--config=/etc/oc-agent-config.yaml"]
    volumes:
      - ./oc-agent-config.yaml:/etc/oc-agent-config.yaml
    ports:
      - 55680:55680
    network_mode: host