receivers:
  opencensus:
    address: ":55680"
    reconnection-delay: 2s

exporters:
  opencensus:
    # mac os / windows
    endpoint: "kube1-1.se.internal:31300"
    # linux
    # endpoint: "localhost:31500"