receivers:
  opencensus:
    address: ":55680"
    reconnection-delay: 2s

exporters:
  opencensus:
    # mac os / windows
    # endpoint: "host.docker.internal:31500"
    # linux
    endpoint: "localhost:31500"