# https://github.com/census-instrumentation/opencensus-service/blob/master/example/k8s.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oc-collector-conf
  labels:
    app: opencensus
    component: oc-collector-conf
data:
  oc-collector-config: |
    receivers:
      opencensus:
        port: 55678
        keepalive:
          server-parameters:
            max-connection-age: 120s
            max-connection-age-grace: 30s            
    # only one exporter possible
    exporters:
      kafka: 
        brokers: ["theodolite-explorviz-cp-kafka:9092"]
        topic: "cluster-dump-spans"

---
apiVersion: v1
kind: Service
metadata:
  name: oc-collector
  labels:
    app: opencesus
    component: oc-collector
spec:
  type: NodePort
  ports:
    - name: opencensus
      port: 55678
      protocol: TCP
      targetPort: 55678
      nodePort: 31300
  selector:
    component: oc-collector
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: oc-collector
  labels:
    app: opencensus
    component: oc-collector
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1
  selector:
    matchLabels:
      app: opencensus 
      component: oc-collector
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8888"
        prometheus.io/scrape: "true"
      labels:
        app: opencensus
        component: oc-collector
    spec:
      containers:
        - command:
            - "/occollector_linux"
            - "--config=/conf/oc-collector-config.yaml"
          env:
            - name: GOGC
              value: "80"
          image: omnition/opencensus-collector:0.1.11
          name: oc-collector          
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 400Mi
          ports:
            - containerPort: 55678
            - containerPort: 13133
          #        - containerPort: 14267
          #        - containerPort: 14268
          #        - containerPort: 9411
          volumeMounts:
            - name: oc-collector-config-vol
              mountPath: /conf
          #        - name: oc-collector-secrets
          #          mountPath: /secrets
          livenessProbe:
            httpGet:
              path: /
              port: 13133
          readinessProbe:
            httpGet:
              path: /
              port: 13133
      nodeSelector:
        env: prod  
      volumes:
        - configMap:
            name: oc-collector-conf
            items:
              - key: oc-collector-config
                path: oc-collector-config.yaml
          name: oc-collector-config-vol
#        - secret:
#            name: oc-collector-secrets
#            items:
#              - key: cert.pem
#                path: cert.pem
#              - key: key.pem
#                path: key.pem
