variables:
  DEFAULT_TAG: exec-docker

default:
  tags:
    - $DEFAULT_TAG

.build-and-deploy:
  stage: deploy:images
    tags:
    - $DEFAULT_TAG
  variables:
    ARCH: "amd64"
    DOCKER_CONTEXT_PATH: $CI_PROJECT_DIR
    IMAGE_NAME: $DOCKERHUB_IMAGE_NAME
    DOCKERFILE_NAME: "Dockerfile"
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CONTAINER_REGISTRY_URL\":{\"auth\":\"$(echo -n ${DOCKERHUB_USERNAME}:${DOCKERHUB_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context=$DOCKER_CONTEXT_PATH
      --dockerfile=${DOCKER_CONTEXT_PATH}/${DOCKERFILE_NAME}
      --destination=$DOCKERHUB_ORGANIZATION/${IMAGE_NAME}:${ARCH}

.retag-dockerhub-image:
  stage: deploy:retagging
  tags:
    - exec-docker
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  rules:
    - if: $MULTI_ARCH_BUILD
      when: never
    - when: on_success
  variables:
    IMAGE_NAME: ${DOCKERHUB_IMAGE_NAME}
    SOURCE_TAG: "latest"
    TARGET_TAG: $CI_COMMIT_SHORT_SHA
  script:
    - crane auth login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD "index.docker.io"
    - crane cp $DOCKERHUB_ORGANIZATION/$DOCKERHUB_IMAGE_NAME:$SOURCE_TAG $DOCKERHUB_ORGANIZATION/$DOCKERHUB_IMAGE_NAME:$TARGET_TAG

.retag-as-multi-arch-dockerhub-image:
  image:
    name: mplatform/manifest-tool:alpine
    entrypoint: [""]
  stage: deploy:retagging
  tags:
    - exec-docker
  rules:
    - if: $MULTI_ARCH_BUILD || $ARM64_BUILD
  variables:
    MANIFEST_PLATFORMS: "linux/amd64,linux/arm64/v8"
    IMAGE_NAME: ${DOCKERHUB_IMAGE_NAME}
    TARGET_TAG: "latest"
    TAG_PREFIX: ""
  script:
    - manifest-tool
      --username ${DOCKERHUB_USERNAME}
      --password ${DOCKERHUB_PASSWORD}
      push from-args
      --platforms ${MANIFEST_PLATFORMS}
      --template ${DOCKERHUB_ORGANIZATION}/${IMAGE_NAME}:${TAG_PREFIX}ARCH
      --target ${DOCKERHUB_ORGANIZATION}/${IMAGE_NAME}:${TARGET_TAG}
