stages:
  - prepare
  - deploy

job1:
  stage: prepare
  tags:
    - exec-docker
  script:
    - echo "Preparing with VARIABLE1 = $VARIABLE1"
    - touch prepared_file.txt
    - echo "Preparation complete" > prepared_file.txt
  artifacts:
    paths:
      - prepared_file.txt
  rules:
    - if: $MULTI-ARCH
      when: never

job2:
  stage: deploy
  tags:
    - exec-docker
  script:
    - echo "Deploying with VARIABLE2 = $VARIABLE2"
    - if [ -f prepared_file.txt ]; then echo "Found prepared file."; else echo "Prepared file not found."; fi
  rules:
    - if: $MULTI-ARCH