stages:
  - prepare
  - deploy

job1:
  stage: prepare
  tags:
    - exec-docker
  script:
    - echo "Preparing with MULTI_ARCH = $MULTI_ARCH"
  rules:
    - if: $MULTI_ARCH

job2:
  stage: deploy
  allow_failure: true
  tags:
    - exec-docker
  script:
    - echo "Deploying with VARIABLE2 = $VARIABLE2"
  needs:
    - job1