stages:
  - docker-manifest

publish-amd64-manifest:
  image:
    name: mplatform/manifest-tool
  stage: docker-manifest
  tags:
    - exec-docker
  only:
    - schedules
  variables:
    MANIFEST_PLATFORMS: "linux/amd64"
  script:
    - "--username ${DOCKERHUB_USER} --password ${DOCKERHUB_PASSWORD} push from-args --platforms ${MANIFEST_PLATFORMS} --template ${DOCKERHUB_ORGA}/${DOCKERHUB_IMAGE_NAME}:ARCH --target ${DOCKERHUB_ORGA}/${DOCKERHUB_IMAGE_NAME}:latest"


publish-multi-arch-manifest:
  extends: publish-amd64-manifest
  only:
    - web
  variables:
    MANIFEST_PLATFORMS: "linux/amd64,linux/arm64/v8"
