stages:
  - prepare
  - deploy

job1:
  stage: prepare
  tags:
    - exec-docker
  script:
    - echo "Preparing with MULTI_ARCH = $MULTI_ARCH"
  rules:
    - if: $MULTI_ARCH

job2:
  stage: deploy
  tags:
    - exec-docker
  script:
    - echo "Deploying with VARIABLE2 = $VARIABLE2"
  rules:
    - when: on_success
    - if: $MULTI_ARCH
      when: never