include: "/.gitlab-ci-docker-manifest.yml"

stages:
  - test
  - deploy:images
  - deploy:retagging

run-pre-commit:
  stage: test
  image: explorviz/pre-commit:latest
  tags:
    - exec-docker
  script:
    - pre-commit run --all-files --config .pre-commit-config.yaml

deploy-petclinic-amd64:
  stage: deploy:images
  tags:
    - exec-docker
  variables:
    ARCH: "amd64"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CONTAINER_REGISTRY_URL\":{\"auth\":\"$(echo -n ${DOCKERHUB_USERNAME}:${DOCKERHUB_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context=$CI_PROJECT_DIR/example-applications/petclinic-demo
      --dockerfile=$CI_PROJECT_DIR/example-applications/petclinic-demo/Dockerfile
      --destination=$DOCKERHUB_ORGANIZATION/$DOCKERHUB_IMAGE_NAME:${ARCH}

deploy-petclinic-arm64:
  extends: deploy-petclinic-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
  variables:
    ARCH: "arm64"
  tags:
    - arm64

deploy-demo-supplier-amd64:
  stage: deploy:images
  tags:
    - exec-docker
  variables:
    ARCH: "amd64"
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      changes:
        - demo-supplier/app.js
        - demo-supplier/Dockerfile
        - demo-supplier/package.json
        - demo-supplier/user.json
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CONTAINER_REGISTRY_URL\":{\"auth\":\"$(echo -n ${DOCKERHUB_USERNAME}:${DOCKERHUB_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context=$CI_PROJECT_DIR/demo-supplier
      --dockerfile=$CI_PROJECT_DIR/demo-supplier/Dockerfile
      --destination=$DOCKERHUB_ORGANIZATION/demo-supplier:${ARCH}

deploy-demo-supplier-arm64:
  extends: deploy-demo-supplier-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
  variables:
    ARCH: "arm64"
  tags:
    - arm64

retag-petclinic-as-latest:
  extends: .retag-dockerhub-image
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: never
  variables:
    SOURCE_TAG: "amd64"
    TARGET_TAG: "latest"

retag-demo-supplier-as-latest:
  extends: .retag-dockerhub-image
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: never
  variables:
    IMAGE_NAME: "demo-supplier"
    SOURCE_TAG: "amd64"
    TARGET_TAG: "latest"

publish-multi-arch-manifest-demo-supplier:
  extends: .retag-as-multi-arch-dockerhub-image
  variables:
    IMAGE_NAME: "demo-supplier"

publish-multi-arch-manifest-petclinic:
  extends: .retag-as-multi-arch-dockerhub-image
