stages:
  - prepare
  - deploy

trigger-multi-project-pipeline:
  stage: prepare
  trigger:
    project: ExplorViz/code/collaboration-service-js
    forward:
      pipeline_variables: true

trigger-metrics-pipeline:
  stage: prepare
  trigger:
    project: ExplorViz/code/metrics-service
    forward:
      pipeline_variables: true


job1:
  stage: prepare
  tags:
    - exec-docker
  script:
    - echo "Preparing with MULTI_ARCH = $MULTI_ARCH"

job2:
  stage: deploy
  tags:
    - exec-docker
  script:
    - echo "Deploying with VARIABLE2 = $VARIABLE2"
  needs:
    - job1
  allow_failure: true