stages:
  - prepare
  - deploy

job1:
  stage: prepare
  tags:
    - exec-docker
  script:
    - echo "Preparing with MULTI_ARCH = $MULTI_ARCH"

job2:
  stage: deploy
  tags:
    - exec-docker
  script:
    - echo "Deploying with VARIABLE2 = $VARIABLE2"
  needs:
    - job1
  allow_failure: true