
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        verbose: true
        exclude: kind/
      - id: end-of-file-fixer
        verbose: true
      - id: trailing-whitespace
        verbose: true
      - id: check-case-conflict
        verbose: true
      - id: fix-byte-order-marker
        verbose: true
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.28.4
    hooks:
      - id: check-jsonschema
        name: "Check Docker Extra Stack"
        language: python
        files: docker/compose/compose.extra.yaml
        types: [yaml]
        args: ["--schemafile", "docker/.json-schemas/extra/main-schema.json"]
      - id: check-jsonschema
        name: "Check Docker Base Stack"
        language: python
        files: docker/compose/compose.base.yaml
        types: [yaml]
        args: ["--schemafile", "docker/.json-schemas/base/main-schema.json"]
      - id: check-jsonschema
        name: "Check Docker Java Stack"
        language: python
        files: docker/compose.yaml
        types: [yaml]
        args: ["--schemafile", "docker/.json-schemas/java/main-schema.json"]
