repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        verbose: true
        exclude: kind/
      - id: end-of-file-fixer
        exclude: example-applications
        verbose: true
      - id: trailing-whitespace
        exclude: example-applications
        verbose: true
      - id: check-case-conflict
        verbose: true
      - id: fix-byte-order-marker
        exclude: example-applications
        verbose: true
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.4.1
    hooks:
      - id: check-jsonschema
        name: "Check Docker-Compose Stack"
        language: python
        files: docker/docker-compose.yml
        types: [yaml]
        args: ["--schemafile", "docker/.json-schemas/main-schema.json"]
