receivers:
  otlp:
    protocols:
      grpc:
        #endpoint: "0.0.0.0:4317"
      http:
        #cors:
         # allowed_origins:
          #- http://*
          #- https://*

processors:
  batch:
    timeout: 5s
    #send_batch_size: 200
  # The batch processor combines multiple incoming telemetry data items into batches.
  # It waits up to 5 seconds or until 200 items are in a batch before sending it further.
  
  attributes:
    actions:
      - key: landscape_token
        value: ffb31fc2-24d3-4718-b72b-6f054055b69e # Inserting your own landscape token!!!
        action: insert
      - key: token_secret
        value: 0CgsRRsidIsv3Yw3 # Inserting your own token secret!!!
        action: insert
      - key: application_name
        value: "meine-express-app"
        action: insert
      - key: application_instance_id
        value: "0"
        action: insert
      - key: application_language
        value: "nodejs"
        action: insert


exporters:
  otlp:
    endpoint: "http://otel-collector:55678"   #otelcol:4317
    tls:
      insecure: true
  otlphttp:
    endpoint: "http://metric-service:8085"
    tls:
      insecure: true

  # debug:
  # zipkin:
  #   endpoint: http://zipkin:9411/api/v2/spans
  # prometheus:
  #   endpoint: "0.0.0.0:9464"
  

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [otlphttp]
