version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - explorviz

  mongo-express:
    build: .
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_MONGODB_SERVE: mongo
    networks:
      - explorviz

  # mongo-express:
  #   build: .
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - explorviz
  #   depends_on:
  #     - mongodb

  # # MongoDB
  # mongodb:
  #   image: mongo:latest
  #   container_name: mongo
  #   environment:
  #     - ME_CONFIG_MONGODB_URL="mongodb://admin:pass@mongo:27017/mydb"
  #     # - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
  #     # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  #     - ME_CONFIG_BASICAUTH_USERNAME="meinBenutzername"
  #     - ME_CONFIG_BASICAUTH_PASSWORD="meinPasswort"
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  #     - SESSION_SECRET="meinGeheimesWort"
  #   volumes:
  #     - mongodb_data:/data/db
  #     - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - explorviz


  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    hostname: zipkin
    ports:
      - "9411:9411"
    environment: 
      - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
    networks:
      - explorviz

      
  # Collector
  collector:
    image: otel/opentelemetry-collector:latest
    hostname: node-collector
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "9464:9464"
      - "4317:4317"
      - "4318:4318"
      
    networks:
      - explorviz
    depends_on:
      - zipkin-all-in-one
      - prometheus
    


  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - explorviz


volumes:
  mongo_data:
    driver: local

networks:
  explorviz:
    name: explorviz
    external: true
