version: '3.8'

services:
  meine-express-app:
    build: .
    ports:
      - "18080:8080"
    networks:
      - explorviz

    # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    hostname: zipkin
    ports:
      - "9411:9411"
    environment: 
      - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
    networks:
      - explorviz

      
  # Collector
  collector:
    image: otel/opentelemetry-collector:latest
    hostname: node-collector
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "9464:9464"
      - "4317:4317"
      - "4318:4318"
      
    networks:
      - explorviz
    depends_on:
      - zipkin-all-in-one
      - prometheus
    


  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - explorviz


networks:
  explorviz:
    name: explorviz
    external: true
