# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "alert.rules"
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
         - targets: ['localhost:9090','cadvisor:8080','node-exporter:9100']

  - job_name: 'adapter-service'
    static_configs:
      - targets:
        - "host.docker.internal:8087" # dev-mode
        - "adapter-service:8087"

  - job_name: 'landscape-service'
    static_configs:
      - targets:
        - "host.docker.internal:8082" # dev-mode
        - "landscape-service:8082"

  - job_name: 'trace-service'
    static_configs:
      - targets:
        - "host.docker.internal:8083" # dev-mode
        - "trace-service:8083"

  - job_name: 'user-service'
    static_configs:
      - targets:
        - "host.docker.internal:8084" # dev-mode
        - "user-service:8084"

  - job_name: 'push-service'
    static_configs:
      - targets:
        - "host.docker.internal:8086" # dev-mode
        - "push-service:8086"


  - job_name: 'collaborative-service'
    static_configs:
      - targets:
        - "host.docker.internal:8085" # dev-mode
        - "collaborative-service:8085"
