kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30001
    # kafka
    hostPort: 30001
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 32680
    # landscape service
    hostPort: 32680
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 31500
    # oc-collector
    hostPort: 31500
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 32681
    # trace service
    hostPort: 32681
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 32682
    # user service
    hostPort: 32682
    listenAddress: "127.0.0.1"
    protocol: TCP
