services:
  collaboration-service:
    hostname: ${COLLABORATION_HOSTNAME}
    image: explorviz/collaboration-service:latest
    ports:
      - "${COLLABORATION_PORT}:4444"
    environment:
      - REDIS_HOST=${REDIS_HOSTNAME}
      - REDIS_PORT=${REDIS_PORT}

  frontend:
    container_name: frontend
    image: explorviz/frontend:latest
    ports:
      - "${FRONTEND_PORT}:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - FRONTEND_HOST_URL=http://${FRONTEND_HOST_NAME}:${FRONTEND_PORT}
      - VITE_CODE_SERV_URL=http://${CODE_HOSTNAME}:${CODE_PORT}
      - VITE_COLLAB_SERV_URL=http://${COLLABORATION_HOSTNAME}:${COLLABORATION_PORT}
      - VITE_SPAN_SERV_URL=http://${SPAN_HOSTNAME}:${SPAN_PORT}
      - VITE_USER_SERV_URL=http://${USER_HOSTNAME}:${USER_PORT}
      - VITE_VSCODE_SERV_URL=http://${FRONTEND_HOST_NAME}:${FRONTEND_PORT}
      - VITE_AUTH_DISABLED_NICKNAME=user-1

  demo-supplier:
    container_name: explorviz-demo-supplier
    image: explorviz/demo-supplier:latest
    hostname: ${DEMO_HOSTNAME}
    ports:
      - "${SPAN_PORT}:8083"
      - "${USER_PORT}:8084"
      - "${CODE_PORT}:8085"

  redis-collab:
    image: redis:7.2.2
    hostname: ${REDIS_HOSTNAME}
    ports:
      - "${REDIS_PORT}:6379"

networks:
  default:
    name: explorviz
