services:
  collaboration-service:
    hostname: collaboration-service
    image: explorviz/collaboration-service:latest
    expose:
      - 4444
    environment:
      - REDIS_HOST=redis-collab
      - REDIS_PORT=6379

  frontend:
    container_name: frontend
    image: explorviz/frontend:latest
    ports:
      - ${FRONTEND_PORT}:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - FRONTEND_HOST_URL=http://${FRONTEND_HOST_NAME}:${FRONTEND_PORT}
      - FRONTEND_HOST_NAME=${FRONTEND_HOST_NAME}
      - CODE_SERV_URL=http://${FRONTEND_HOST_NAME}:${FRONTEND_PORT}
      - LANDSCAPE_URL=http://${SPAN_HOSTNAME}:${SPAN_PORT}
      - TRACE_URL=http://${SPAN_HOSTNAME}:${SPAN_PORT}
      - TIMESTAMPS_URL=http://${SPAN_HOSTNAME}:${SPAN_PORT}
      - USER_URL=http://${USER_HOSTNAME}:${USER_PORT}
      - COLLABORATION_URL=http://${COLLABORATION_HOSTNAME}:${COLLABORATION_PORT}
      - AUTH0_LOGO_URL=${AUTH0_LOGO_URL}
      - AUTH0_CALLBACK_URL=${AUTH0_CALLBACK_URL}
      - AUTH0_LOGOUT_URL=${AUTH0_LOGOUT_URL}
      - VSCODE_SERV_URL=http://${FRONTEND_HOST_NAME}:${FRONTEND_PORT}
      - NO_AUTH_USER_NICKNAME=user-1

  demo-supplier:
    container_name: explorviz-demo-supplier
    image: explorviz/demo-supplier:latest
    expose:
      - 8083

  redis-collab:
    image: redis:7.2.2
    expose:
      - 6379

networks:
  default:
    name: explorviz
