services:
  frontend:
    hostname: frontend
    image: explorviz/frontend:html
    depends_on:
      - demo-supplier
      - collaboration-service
    ports:
      - 8080:80
    environment:
      - FRONTEND_HOST_URL=http://localhost:8080 # Determines base URL for backend services that frontend calls
      - FRONTEND_HOST_NAME=localhost
      - CODE_SERV_URL=http://localhost:8080 # This and the following URLs are used for nginx config
      - LANDSCAPE_URL=http://demo-supplier:8083
      - TRACE_URL=http://demo-supplier:8083
      - TIMESTAMPS_URL=http://demo-supplier:8083
      - USER_URL=http://demo-supplier:8084
      - COLLABORATION_URL=http://localhost:4444
      - VSCODE_SERV_URL=http://localhost:8080
  demo-supplier:
    container_name: explorviz-demo-supplier
    image: explorviz/demo-supplier:html
    expose:
      - "8083-8085"

  collaboration-service:
    hostname: collaboration-service
    image: explorviz/collaboration-service:html
    expose:
      - "4444"
    environment:
      - REDIS_HOST=redis-collab
      - REDIS_PORT=6379

  redis-collab:
    image: redis:7.2.2
    expose:
      - "6379"

networks:
  default:
    name: nginx-proxy
