version: "3.5"
services:
  collaboration-service:
    hostname: collaboration-service-js
    image: explorviz/collaboration-service-js:latest
    #ports:
    #- ${COLLABORATION_PORT}:4444
    environment:
      - REDIS_HOST=redis-collab
      - REDIS_PORT=6379

  frontend:
    container_name: explorviz-frontend
    image: explorviz/explorviz-frontend:dev-noauth
    ports:
      - ${FRONTEND_PORT}:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - FRONTEND_HOST_URL=http://${FRONTEND_HOST_NAME}:${FRONTEND_PORT}
      - FRONTEND_HOST_NAME=${FRONTEND_HOST_NAME}
      - LANDSCAPE_URL=http://${LANDSCAPE_HOSTNAME}:${LANDSCAPE_PORT}
      - TRACE_URL=http://${TRACE_HOSTNAME}:${TRACE_PORT}
      - USER_URL=http://${USER_HOSTNAME}:${USER_PORT}
      - COLLABORATION_URL=http://${COLLABORATION_HOSTNAME}:${COLLABORATION_PORT}
      - AUTH0_LOGO_URL=${AUTH0_LOGO_URL}
      - AUTH0_CALLBACK_URL=${AUTH0_CALLBACK_URL}
      - AUTH0_LOGOUT_URL=${AUTH0_LOGOUT_URL}
      - VSCODE_SERV_URL=http://${FRONTEND_HOST_NAME}:${FRONTEND_PORT}
      - NO_AUTH_USER_NICKNAME=user-1

  demo-supplier:
    container_name: explorviz-demo-supplier
    image: explorviz/demo-supplier
    #ports:
    #  - 8082:8082
    #  - 8083:8083
    #  - 8084:8084

  redis-collab:
    image: redis:7.2.2
    expose:
      - 6379

networks:
  default:
    name: explorviz
