# Do not name the service or pods "schema-registry": https://github.com/confluentinc/schema-registry/issues/689#issuecomment-354485274

apiVersion: apps/v1
kind: Deployment
metadata:
  name: schemaregistry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:5.5.0
          env:
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka:9092
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: schemaregistry
spec:
  selector:
    app: schema-registry
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
