apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorviz-adapter-service
  labels:
    app: explorviz-adapter-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorviz-adapter-service
  template:
    metadata:
      labels:
        app: explorviz-adapter-service
    spec:
      containers:
      - name: explorviz-adapter-service
        image: explorviz/adapter-service-jvm:jib
        ports:
          - containerPort: 80
        imagePullPolicy: Always
      nodeSelector:
        env: prod 
