# docker-compose --env-file .env-custom up -d

# docker-compose --env-file .env-custom down -v

services:
  ocelot-agent:
    image: inspectit/inspectit-ocelot-agent:2.5.6
    container_name: ocelot-agent-petclinic
    networks:
      - explorviz
    volumes:
      - agent-vol:/agent

  plantuml:
    image: plantuml/plantuml-server:jetty-v1.2022.7
    depends_on:
      - ocelot-agent
    ports:
      - ${PLANTUML_EXTERNAL_PORT}:8080
    networks:
      - explorviz
    environment:
      - LANDSCAPE_TOKEN_ID=${LANDSCAPE_TOKEN_ID}
      - LANDSCAPE_TOKEN_SECRET=${LANDSCAPE_TOKEN_SECRET}
    volumes:
      - agent-vol:/agent
      - ./inspectit.yml:/agent/inspectit.yml
    #entrypoint: ["sh", "-c", "java -Dinspectit.config.file-based.path=\"/agent/\" -javaagent:/agent/inspectit-ocelot-agent.jar -jar /opt/plantuml.jar"]
    entrypoint:
      [
        "java",
        "-Dinspectit.config.file-based.path=/agent",
        "-javaagent:/agent/inspectit-ocelot-agent.jar",
        "-jar",
        "/usr/local/jetty/start.jar",
      ]

volumes:
  agent-vol:

networks:
  explorviz:
    name: explorviz
    external: true
