
extraEnvVars: 
  - name: KAFKA_CFG_LOG_MESSAGE_TIMESTAMP_TYPE
    value: "LogAppendTime"

externalAccess:
  enabled: true
  service:
    type: NodePort
    nodePorts: 
      - 30001
    domain: "127.0.0.1"
  autoDiscovery:
    enabled: false

metrics:
  ## Prometheus Kafka Exporter: exposes complimentary metrics to JMX Exporter
  ##
  kafka:
    enabled: false
  jmx:
    enabled: true

persistence:
  enabled: false

serviceAccount:
  create: true

rbac:
  create: true