
extraEnvVars: 
  - name: KAFKA_CFG_LOG_MESSAGE_TIMESTAMP_TYPE
    value: "LogAppendTime"


replicaCount: 1

externalAccess:
  enabled: true
  service:
    type: NodePort
    nodePorts: 
      - 30011
    #  - 30012
    #domain: "127.0.0.1"
  #autoDiscovery:
  #  enabled: true

metrics:
  ## Prometheus Kafka Exporter: exposes complimentary metrics to JMX Exporter
  ##
  kafka:
    enabled: false
  jmx:
    enabled: true

persistence:
  enabled: true

serviceAccount:
  create: true

rbac:
  create: true

nodeExporter:
  ## If false, node-exporter will not be installed
  ##
  enabled: false
