
extraEnvVars: 
  - name: KAFKA_CFG_LOG_MESSAGE_TIMESTAMP_TYPE
    value: "LogAppendTime"

externalAccess:
  enabled: true
  service:
    type: NodePort
  autoDiscovery:
    enabled: true

serviceAccount:
  create: true

rbac:
  create: true