# docker-compose --env-file .env-custom up -d

# docker-compose --env-file .env-custom down -v

version: "3.5"
services:
  ocelot-agent:
    image: inspectit/inspectit-ocelot-agent:1.9.0
    container_name: ocelot-agent-custom-app
    networks:
      - explorviz
    volumes:
      - agent-vol:/agent

  sample-application:
    image: explorviz/sample-application
    container_name: sample-application
    depends_on:
      - ocelot-agent
    networks:
      - explorviz
    environment:
      - LANDSCAPE_TOKEN_ID=${LANDSCAPE_TOKEN_ID}
      - LANDSCAPE_TOKEN_SECRET=${LANDSCAPE_TOKEN_SECRET}
    volumes:
      - agent-vol:/agent
      - ./inspectit.yml:/agent/inspectit.yml
    entrypoint: [
        "sh",
        "-c",
        '
        java
        -Dinspectit.config.file-based.path="/agent/"
        -javaagent:/agent/inspectit-ocelot-agent.jar
        -jar /app.jar',
      ]

volumes:
  agent-vol:

networks:
  explorviz:
    name: explorviz
