version: "3.5"

services:
  vs-code:
    image: explorviz/vs-code:dev
    ports:
      - 3001:80
    links:
      # necessary for mixed content (= iframe of frontend) that is not served via HTTPS
      - "frontend:localhost"
    environment:
      - VS_CODE_BACKEND_URL=http://localhost:${VSCODE_PORT}
      - FRONTEND_URL=http://localhost:${FRONTEND_PORT}
    volumes:
      - ./projects:/home/workspace
    command: --port 80

  collaboration-service:
    container_name: collaboration-service
    image: explorviz/collaboration-service-js:latest
    ports:
      - ${COLLABORATION_PORT}:4444
    environment:
      - EXPLORVIZ_LOG_LVL=DEBUG
      - REDIS_HOST=${REDIS_HOSTNAME}
      - REDIS_PORT=${REDIS_PORT}

  demo-supplier:
    container_name: explorviz-demo-supplier
    image: explorviz/demo-supplier:latest
    ports:
      - ${LANDSCAPE_PORT}:8082
      - ${USER_PORT}:8084

  redis-collab:
    image: redis:7.2.2
    expose:
      - ${REDIS_PORT}

  vs-code-backend:
    container_name: vs-code-backend
    image: explorviz/vs-code-backend:dev
    environment:
      - EXPERIMENT_MODE=true
    ports:
      - ${VSCODE_PORT}:3000

  frontend:
    image: explorviz/explorviz-frontend:dev-noauth
    ports:
      - ${FRONTEND_PORT}:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - FRONTEND_HOST_URL=http://${FRONTEND_HOST_NAME}:${FRONTEND_PORT}
      - FRONTEND_HOST_NAME=${FRONTEND_HOST_NAME}
      - LANDSCAPE_URL=http://${LANDSCAPE_HOSTNAME}:${LANDSCAPE_PORT}
      - TRACE_URL=http://${TRACE_HOSTNAME}:${TRACE_PORT}
      - TIMESTAMPS_URL=http://${TRACE_HOSTNAME}:${TRACE_PORT}
      - USER_URL=http://${USER_HOSTNAME}:${USER_PORT}
      - VSCODE_SERV_URL=http://${VSCODE_HOSTNAME}:${VSCODE_PORT}
      - COLLABORATION_URL=http://${COLLABORATION_HOSTNAME}:${COLLABORATION_PORT}
      - COLLABORATION_SOCKET_PATH=/v2/vr/
      - AUTH0_LOGO_URL=${AUTH0_LOGO_URL}
      - AUTH0_CALLBACK_URL=${AUTH0_CALLBACK_URL}
      - AUTH0_LOGOUT_URL=${AUTH0_LOGOUT_URL}
      - NO_AUTH_USER_NICKNAME=user-1

networks:
  default:
    name: explorviz
