version: '3'

services:
  explorviz-reverse-proxy:
    container_name: explorviz-reverse-proxy
    hostname: reverse
    image: nginx
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/ssl/private