receivers:
  otlp:
    protocols:
      grpc:
        endpoint: :55678

exporters:
  file:
    path: "/etc/otel/telemetry.json"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [file]
    metrics:
      receivers: [otlp]
      exporters: [file]
    logs:
      receivers: [otlp]
      exporters: [file]
