receivers:
  otlpjsonfile:
    include:
      - "/etc/otel/*.json"

processors:
  attributes/add_default_landscape_token:
    actions:
      - key: landscape_token
        value: "mytokenvalue"
        action: insert
      - key: token_secret
        value: "mytokensecret"
        action: insert

exporters:
  kafka:
    protocol_version: 2.0.0
    brokers:
      - kafka:9092
    topic: otlp_spans
  debug:
    verbosity: detailed

extensions:
  zpages:
    endpoint: :55679

service:
  extensions:
    - zpages
  pipelines:
    traces:
      receivers:
        - otlpjsonfile
      processors:
        - attributes/add_default_landscape_token
      exporters:
        - debug
        - kafka
