services:
  frontend:
    container_name: frontend
    image: explorviz/frontend:latest
    environment:
      - VIRTUAL_HOST=${LETSENCRYPT_HOSTNAME}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOSTNAME}
      - FRONTEND_HOST_URL=http://${FRONTEND_HOSTNAME}:${FRONTEND_PORT} # Determines base URL for backend services that frontend calls
      - FRONTEND_HOSTNAME=${FRONTEND_HOSTNAME}
      - CODE_AGENT_URL=http://${MOCK_HOSTNAME}:${PERSISTENCE_PORT}
      - PERSISTENCE_SERV_URL=http://${MOCK_HOSTNAME}:${PERSISTENCE_PORT}
      - COPILOT_SERV_URL=http://${MOCK_HOSTNAME}:${PERSISTENCE_PORT}
      - USER_SERV_URL=http://${MOCK_HOSTNAME}:${USER_PORT}
      - VSCODE_SERV_URL=http://${MOCK_HOSTNAME}:${PERSISTENCE_PORT}
      - KEYCLOAK_URL=http://${MOCK_HOSTNAME}:${PERSISTENCE_PORT}

  backend-mock:
    container_name: explorviz-backend-mock
    image: explorviz/backend-mock:latest
    expose:
      - 8084
      - 8085

networks:
  default:
    name: nginx-proxy
