services:
  ## Demo-Supplier ##

  demo-supplier:
    container_name: explorviz-demo-supplier-extended
    image: demo-supplier/extendeddataset
    networks:
      - explorviz
    ports:
      - 8083:8083
      - 8084:8084

networks:
  explorviz:
    name: explorviz
    external: true
