receivers:
  otlp:
    protocols:
      grpc:
        endpoint: :55678

exporters:
  kafka:
    protocol_version: 2.0.0
    brokers:
      - kafka:9092
    topic: otlp_spans
  kafka/2:
    protocol_version: 2.0.0
    brokers:
      - kafka:9092
    topic: otlp_logs

  logging:
    loglevel: debug

extensions:
  zpages:
    endpoint: :55679

service:
  extensions:
    - zpages
  pipelines:
    logs:
      receivers:
        - otlp
      exporters:
        - kafka/2
    traces:
      receivers:
        - otlp
      exporters:
        - kafka
