receivers:
  opencensus:
    endpoint: 0.0.0.0:55678

exporters:
  logging:
  kafka:
    brokers: ["kafka:9092"]
    topic: "cluster-dump-spans"
    protocol_version: 2.5.0

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [opencensus]
      processors: [batch]
      exporters: [logging, kafka]
