version: '3.8'

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - explorviz

  mongo-express:
    build: .
    ports:
      - ${EXTERNAL_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      ME_CONFIG_MONGODB_SERVE: mongo
    networks:
      - explorviz


  # # Zipkin
  # zipkin-all-in-one:
  #   image: openzipkin/zipkin:latest
  #   hostname: zipkin
  #   ports:
  #     - "9411:9411"
  #   environment: 
  #     - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
  #   networks:
  #     - explorviz

      
  # Collector
  collector:
    image: otel/opentelemetry-collector:latest
    hostname: node-collector
    env_file:
      - ./.env
    environment:
      - LANDSCAPE_TOKEN=${LANDSCAPE_TOKEN}
      - TOKEN_SECRET=${TOKEN_SECRET}
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "9464:9464"
      - "4317:4317"
      - "4318:4318"
      
    networks:
      - explorviz
    # depends_on:
    #   - zipkin-all-in-one
    #   - prometheus
    


  # # Prometheus
  # prometheus:
  #   image: prom/prometheus:latest
  #   hostname: prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - explorviz


volumes:
  mongo_data:
    driver: local

networks:
  explorviz:
    name: explorviz
    external: true
