version: '3.8'

services:

  # Mongo database
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - explorviz

  # Mongo application
  mongo-express:
    build: .
    ports:
      - ${EXTERNAL_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      ME_CONFIG_MONGODB_SERVE: mongo
    networks:
      - explorviz
      
  # Collector
  collector:
    image: otel/opentelemetry-collector:latest
    hostname: node-collector
    env_file:
      - ./.env      # required to use the environment variables
    environment:
      - LANDSCAPE_TOKEN=${LANDSCAPE_TOKEN}
      - TOKEN_SECRET=${TOKEN_SECRET}
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "4317:4317"   # the port for gRPC transports, which we do not use, but maybe necessary in the future
      - "4318:4318"   # the port for HTTP transports
      
    networks:
      - explorviz

volumes:
  mongo_data:
    driver: local

networks:
  explorviz:
    name: explorviz
    external: true
