# Contains non-Java ExplorViz components

# Start with top-level compose.yaml.

include:
  - ./compose.aux.yaml

services:

  collaboration-service-js:
    hostname: collaboration-service-js
    image: explorviz/collaboration-service-js:latest
    env_file:
       - path: ../.env
       - path: ../.env-custom
         required: false
    #ports:
    #- ${COLLABORATION_PORT}:4444
    environment:
      - REDIS_HOST=redis-collab
      - REDIS_PORT=6379

  frontend:
    hostname: explorviz-frontend
    image: explorviz/explorviz-frontend:dev-noauth
    env_file:
       - path: ../.env
       - path: ../.env-custom
         required: false
    depends_on:
      - span-service
      - user-service
      - collaboration-service-js
    ports:
      - ${FRONTEND_PORT}:80
    environment:
      - FRONTEND_HOST_URL=http://${FRONTEND_HOST_NAME}:${FRONTEND_PORT}
      - FRONTEND_HOST_NAME=${FRONTEND_HOST_NAME}
      - LANDSCAPE_URL=http://${SPAN_HOSTNAME}:${SPAN_PORT}
      - TRACE_URL=http://${SPAN_HOSTNAME}:${SPAN_PORT}
      - TIMESTAMPS_URL=http://${SPAN_HOSTNAME}:${SPAN_PORT}
      - USER_URL=http://${USER_HOSTNAME}:${USER_PORT}
      - COLLABORATION_URL=http://${COLLABORATION_HOSTNAME}:${COLLABORATION_PORT}
      - VSCODE_SERV_URL=http://${FRONTEND_HOST_NAME}:${FRONTEND_PORT}
      - AUTH0_LOGO_URL=${AUTH0_LOGO_URL}
      - AUTH0_CALLBACK_URL=${AUTH0_CALLBACK_URL}
      - AUTH0_LOGOUT_URL=${AUTH0_LOGOUT_URL}
      - NO_AUTH_USER_NICKNAME=${NO_AUTH_USER_NICKNAME}
